name: ratingsrantsandraves
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8892169783357531
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#0f0d1a'
    - '#3f3734'
    - '#dad9d4'
    - '#909694'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.1491412604227662
purpose: []
