name: ratingsrantsandraves
favicon: null
layout_spectrum: 0.80126
typography_spectrum: 0.04959
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d0802'
    - '#4b6574'
    - '#b7b082'
    - '#a46f40'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
