typography_spectrum: 0.04959
color:
  brandColors:
    - '#040404'
    - '#b9af8b'
    - '#575850'
    - '#daee71'
    - '#a75d00'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24299
analytics:
  google: null
  facebook: null
  twitter: null
name: ratingsrantsandraves
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: >-
  New England Shirt Company talking about Donald Trump Clothes being made
  somewhere outside the USA.....the whole story.
description: >-
  New England Shirt Company basic white shirt 3 times the price of Donald Trump
  shirt
purpose: []
