name: ratingsrantsandraves
favicon: null
layout_spectrum: 0.24299
typography_spectrum: 0.04959
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#b9af8b'
    - '#575850'
    - '#daee71'
    - '#a75d00'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
