name: ratingsrantsandraves
favicon: null
layout_spectrum: 0.5009
typography_spectrum: 0.04959
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5586d2'
    - '#ecf1f4'
    - '#171f2c'
    - '#c2bfb6'
    - '#cc243e'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
